language: java

jdk:
- openjdk11

sudo: false
env:
  global:
  #key for github
  #GITHUB_OAUTH_TOKEN
  - secure: "nQVOFCzO6QRCgJd5nqrl2ptm0QB5yPXYqygTVu1aKME+UyJTnjuiHw/Et90/NI5nKh7GmS5xg1TxfdSXD48XUYH+SfDwoKSimZ9jNwWG6ZnxajPXkMiVkME15Wjd6w5w9LBi9wXYoIgwZOM9gf2TDmwx/DJOlqA43SNMkmMtpO2THQfrHQbkOIvOlFO3BQ5ueMtyXA9tNjKCmQHb3mY/7cCeYtj3n7/OpSwD4O7ao7koSnOV7LOt9vwUf3bMFhlMltH/WGJwk01wCMSvxDKNkPsRKSfxiy/6S9EVgy97QCpMLTguCpd42btpuCr8jpv7k8lQW6ATAmILmzPCOOfPkWFafVhBbvD8uvtT2QbbR+z6gfMz2aeAZT6DhqtNyUxXDKxoIMz2oRPlwiQJi4owpuLNaHjzNCrf/Wl7qZnmwQmjOuhfDvWFKZBoXaGRh4dybTMUAmuty1PhufVWlbJuBquWDPWV8eJy5VgcVpiRcImqOIbeq8G6Q+muzek/bt+fI1KsY5cTRebqguT5k+3/SLeNXV/zDxAebIEAWPjL9Sjgy6AFxUPuwb7tWdG8SEjK/PYWkcbbQqcfo7ZvF+8GEW+LiGI7Y7KakhGz1XnTTxLcMAFy91E+wkB33kL1bv4bNwC6FHpCVLqHE3LpbIvM0LqcRBPA5mgy+ZqiUUGBbO8="
  - environment=test
  #sonatype credentials
  #OSSRH_JIRA_USERNAME
  - secure: "u3dCTHf3/lBfFMT/jLGdj81F/8+mm9wwnwPibzyHd917udLwsn9fXTXlbJqMhsCRHmchsKwnGSumqCzum25zlYm37mzOHsu60Mkex2WpJP3qa9ZA5D3Ci1Vk8W3dopvMi7nY6kcg6gVXs32tYvBVxGhdBKSXv4R12uzPzgjcOZz0Vc+aA459CEXKd73+/imTkBFdDKf0i40ZCPtVQWh2a6hfmgmFi6aRRdk/I/iP7Pml7fhFKcd5kt2vZgMHORxzEk8dYAypUun8800+B3atxqw6Ih3O7HJSIQMUAyz021Zrrn+gfU4oy/OploEOaH6tU7tgc1W5Hd28IJQycCiO4wSXC3xT4aMCXUKvbccNSxWZiB9dqR2YSw62QD88xpdy0eLK2r+vVG7NQ0eVvnzVxPov97ip469mZQsYRE6pxvzOvLeuUCgoz6MLkBVkVm/RwqSeTGv8KxvfhW+aRFafGdcODHPKILBDBmfR+miql6uVQoGwPOPVJfFjuzTqMKlwX0zvqt8EUE38hmj20hMrXdIC/7wZ1DvMnIwwmApMoQbeFUsWLi1HK1OK6C3EzuSBsbsvLln16youIumbB5JS+Me72Cdn42OD7gh89sUMKq6JhDBAEWa3qpHS0fVL0Gb+sfMzdv2oNkylB/c/vAg3aBaH9cYbNkfA/fHYQN7a5Lw="
  #OSSRH_JIRA_PASSWORD
  - secure: "VeoYA5B9rI2Xp+0x2GMnm7XbqQtgbYa14kqz2ON9l2R1bZWxuXwyF+gw1z7gy39x3Jc3Qe5Szm/DzBdsPOUcUdLhOw/O4IuApORDmphkWzwL68Jjai/TybCW0Jh+DGfvM276mO10Tg3btUxFuYG9020m9zc2HqIk9CwbJPKO7NpP2Oz92eUXzJzPL8oCeNJ6I8kqazsCgruVhuq5YAfUew4mnyBYQbaRKB0MxNHGyysL7muc9pB9lFBBVp9on2kXntDdz89Krnc/eMudo1q7rLv0Es/MVMvBc8iT6A9WNyS7M08buQYNXn0GR4ExM+iFO056ZlQPlwD8jlLSOSmlmiukLkQv/IiNbUw/wCpdiExmRKnGRuNceoQNgKiueXsgC7vbtsHVm3nCYVtwrxZpTm0ks8pGKfDdfC8CFFPciRxJmDpVr8puhXtoXnnJQn1qPb5C/GoEWi+zuTlaP1TxzLRt9Jx3FyUuGDyloTeSwiGjVIG8159UpTyjIvb18yP1dFOuSZCLtcaJmVSDpqKk5M3HMUNUB0EO3TrATlYDYL5g8P4yKYhMTJJZq64EJAN4v2MZw0TbmDMIZfjJaOIw3enJfdAJuQHjtetIGj5hDpQkCoWnzd8PVDWmKwdYsR1bjgdXAm/K0rwPad2oBQD5gFQ3MduBJrc8W4sV8SYFsAY="
  #signing key
  #GPG_KEY_NAME
  - secure: "tVX2gqYJFctZ71IW6TrNX85Fn885ibfUQDeZm+7o2Kz17ShmZCQ7YseJzMbvTfSeHiSeKpGF6LeN4XyM8V9m4DrQWtYbWTRaTnoBEm2caRUiEvTpUfjBQdxUkW+bYYBBcDwZUrtH0ZUD+aZno/NI4zV9rjSn+8WM22AlD8HWftO/OQZseePBvUZMgc6rnZ7l7bw5FEFKgYVN24MEatoHHef/MzDc3k4/idD/tpggEVlKYENfP4h02iZDggePbHirb/Vacl44pYqEIW/F8A737xeXOcvh2rHl5R7Yb7W2qkPBUHbdrKJs04g+JeZqecwwLsWAOFFUgCPHgBoLtLjFBxhNfkXiohZF7KTbaLwXX22CEtf90/LcoZbIRBYFvaTnkrMghihHlnjJolhwGTmJahVsCWRUi92b5obz27B2mrkWEvn7ZLdlkHGSV15IPT5lg7lQDS+o9R++oodEDINX5Tag6FcLOvZt68Rb/5KBIZUiaB00AEG1FpYNBh5qH/pQgZKH222Q2qorBJbijwPpvQUMfJPnf/UASHrUf7g1lvC/brYE4F9xWKI1W0J/fv77CHymaYQd6mtewlTW6BfLC9uUenkXl+oR6jRd3lZ/ydZLee4tanf6kq6JSXkAK1POQk6Qza2mKIsFIg9ZpT8zteHZJTJbe8Yga4a6hjLFLFc="
  #GPG_PASSPHRASE
  - secure: "P1LGbyFdZvRjY5Sb8T88Ahw7JzON3alkSm6UaZT5tIWvahhVvgMrj/Z5qFr2H1lOuitGBfxnpc39mFbZOvzJTE015UNmmIE1JXKbp/8XfdHcMqubcTrYTdfesjpXnFE4SW9J5OD6jXBtAFrcdEjMED5zOP6rNd3xBz3TzF7KSxHBG8PiEIcum1YPLdYAt8IrbpMK/8vigYefb1yur3haKkxmB4HHtSpMw1/kr6Q5Ku7eSQCXef3FNcs5NlOaEJA+NmCudpofPaMmCDyUPelvF6pZLWDIwlvLL8OPEKZwEl6WoI/roW8zBo3mOa90orFRs5mqoGbCSRPbq+gM1rjjvPUPD4ltmBkJQ5r64Yo67zD3j4+1NKlnYVTNysNp1RTqIs49CmSbLLv40twGc7iERlHRBvcbAJ/C83AthaZINnnJkYC7SEN7m93UVqYLUHf16YU17CmDGMTHrxHE0i8ncV44UZN3lnwcoGB1GSrZL9tDZU/WZG6xmXNGbAZPQIaGrqyXANsfBxrL91pGNhySjR7hxUdaxKCpSK36qLBfrSLwggeSkBTqGkgWBf6kCRDfDOoQ/iqhWwiTwpOXzM/uNUJ77RwrxMVH/Pp1Tme6Uhw+CH25JtnNRyH/33y7eBETUQJtEgcm+YcJJ80YlW3VAgy06ulrLPSWdj8H8A8qHw8="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "rFfr31Adjl0qacjYIPgBcHnqVUIOjMziXcyojNwkBJY95UAiBjpkjFCLqVUn1TVHr8XHNX/R9coitgkh93oxrLgIpqOlGdA8Doxlg0PvlYm2AQi5xpnQSEZyVS7fkSeua5Gnd7oNe5fcAY3cWFgw1tcRRFr4yvVcy8hsG3OyVdDe0eeiMRA/GqbUPzqUW8D3d8fKaHWthQV4s+AlQgujZA2oGo9CLuz/gmAAvJfPUiNUERxKBW23SyTC4Yqt+jHTbuzeWCa+a9Qx5Pvlbuv4iuARgvJj2iwiSbsS5ckCFpWIVbzABfLnUl7nrkEp+F2TTOlYZ0YIop7Q3d536pRzFz6OikdQoSctVSTa3P5fZIQGTKhNOaaY0dpzd4nWhZAEPlRRRv8v9KoGZL+8ePpZ1pgnJrfueyG5lD/B29uu+Hkm+wUWy6RVF4pflGU0wHNgOtkiKpotcqMkyUGirLIiRfAQK+/yb6UMs4CpHDYQbW3gYqbkJGBM6HZEJ40nbjT5eh3j2QXTxI7oUOA9uB9ZSrpTUQIGmU2jYykSVldePNoISG7KyXaRxqaM1ms78irYmXtI7zpNqq5DjHb4qGYrLrBh7HOyKCdp7eAfUsNNp2PqxOt+UzTvk4lVQutZcjEjp1dRIwRjpqBTzQMCa1u0ozMqm+lqEohkNNFc5+yvQOk="

branches:
  only:
  - develop
  - master

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
- travis_wait 50 mvn clean jacoco:prepare-agent install jacoco:report -P !build-extras
- mvn site -Djacoco.skip -DskipTests -P !build-extras
- sonar-scanner

cache:
  directories:
  - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
- ./cd/before-deploy.sh
- ./cd/deploy.sh
